// Generated by CoffeeScript 1.6.3
(function() {
  var BiggerPicture;

  BiggerPicture = BiggerPicture || {};

  BiggerPicture.App = (function() {
    function App() {
      var images, ss;
      images = $(".bpImageTop, .bpBoth");
      ss = new BiggerPicture.Gallery(images);
    }

    return App;

  })();

  setTimeout(function() {
    return new BiggerPicture.App();
  });

  0;

  BiggerPicture = BiggerPicture || {};

  BiggerPicture.Gallery = (function() {
    Gallery.prototype.slides = [];

    Gallery.prototype.current_index = 0;

    Gallery.prototype.container = $("<div />", {
      "class": "bigger-picture"
    });

    Gallery.prototype.overlay = $("<div />", {
      "class": "bigger-picture-overlay"
    });

    Gallery.prototype.ul = $("<ul />", {
      "class": "bigger-picture-list"
    });

    function Gallery(images) {
      var image, _i, _len;
      for (_i = 0, _len = images.length; _i < _len; _i++) {
        image = images[_i];
        this.set_up_image(image);
      }
      this.container.append(this.overlay, this.ul);
      $("body").append(this.container);
      this.set_up_listeners();
      this.show_current();
    }

    Gallery.prototype.set_up_image = function(image) {
      var caption, id, src;
      image = $(image);
      src = image.find(".bpImage").first().prop("src");
      caption = image.find(".bpCaption");
      caption.find(".photoNum").remove();
      caption.find(".cf, a").remove();
      caption = caption.text();
      id = "slide-" + this.slides.length;
      this.ul.append($("<li >", {
        id: id
      }));
      return this.slides.push(new BiggerPicture.Slide(src, caption, id));
    };

    Gallery.prototype.show_current = function() {
      return this.slides[this.current_index].show_slide($(window).height(), $(window).width());
    };

    Gallery.prototype.hide_current = function() {
      return this.slides[this.current_index].hide_slide();
    };

    Gallery.prototype.set_up_listeners = function() {
      var _this = this;
      return $("body").on("keydown", function(evt) {
        return _this.test_keypress(evt);
      });
    };

    Gallery.prototype.test_keypress = function(evt) {
      var kc, to;
      kc = evt.keyCode;
      to = -9999;
      if ((kc === 39 || kc === 40)) {
        to = this.current_index < this.slides.length - 1 ? this.current_index + 1 : 0;
      } else if ((kc === 37 || kc === 38)) {
        to = this.current_index > 0 ? this.current_index - 1 : this.slides.length - 1;
      }
      if (to >= 0) {
        evt.preventDefault();
        this.hide_current();
        this.current_index = to;
        return this.show_current();
      }
    };

    return Gallery;

  })();

  BiggerPicture = BiggerPicture || {};

  BiggerPicture.Slide = (function() {
    Slide.prototype.pending_show = null;

    Slide.prototype.loaded = false;

    Slide.prototype.lw = -1;

    Slide.prototype.lh = -1;

    function Slide(src, caption, id) {
      this.src = src;
      this.caption = caption;
      this.id = id;
      this.create_image();
    }

    Slide.prototype.get_resize_dimensions = function(w, h, tw, th) {
      var scale;
      if (tw > w || th > h) {
        scale = tw / w < th / h ? tw / w : th / h;
        return {
          w: Math.floor(w * scale),
          h: Math.floor(h * scale)
        };
      } else {
        return {
          w: w,
          h: h
        };
      }
    };

    Slide.prototype.create_image = function() {
      var _this = this;
      this.img = new Image();
      this.img.onload = function(evt) {
        return _this.image_loaded();
      };
      return this.img.src = this.src;
    };

    Slide.prototype.image_loaded = function() {
      this.loaded = true;
      this.width = this.img.width;
      this.height = this.img.height;
      if (this.pending_show) {
        return this.show_slide(this.pending_show.h, this.pending_show.w);
      }
    };

    Slide.prototype.show_slide = function(h, w) {
      if (!this.loaded) {
        return this.pending_show = {
          h: h,
          w: w
        };
      } else {
        if (!this.element || this.lh !== h || this.lw !== w) {
          this.build_element(h, w);
        }
        return this.element.fadeIn("fast");
      }
    };

    Slide.prototype.hide_slide = function() {
      return this.element.fadeOut("fast");
    };

    Slide.prototype.build_element = function(h, w) {
      var new_wh;
      if (!this.element) {
        this.element = $("#" + this.id);
      }
      this.lh = h;
      this.lw = w;
      new_wh = this.get_resize_dimensions(this.width, this.height, this.lw, this.lh);
      this.img = $("<img />", {
        src: this.src,
        width: new_wh.w,
        height: new_wh.h
      });
      return this.element.html(this.img);
    };

    return Slide;

  })();

}).call(this);
