// Generated by CoffeeScript 1.6.3
(function() {
  var BigPicture;

  BigPicture = (function() {
    function BigPicture() {
      var container, containers, image_el, images, _i, _len;
      containers = $(".bpBody, .bpImageTop, .bpBoth, .t402-elided-image.bpImage");
      images = [];
      for (_i = 0, _len = containers.length; _i < _len; _i++) {
        container = containers[_i];
        container = $(container);
        image_el = container.find("img").first();
        images.push({
          image_el: image_el,
          src: image_el.attr('src'),
          caption: container.find(".bpCaption").remove("a, div").text()
        });
      }
      new BiggerPicture.Gallery(images);
    }

    return BigPicture;

  })();

  setTimeout(function() {
    return new BigPicture();
  });

  0;

}).call(this);
