// Generated by CoffeeScript 1.6.3
(function() {
  var theChive;

  theChive = (function() {
    function theChive() {
      var container, containers, image_el, images, _i, _len;
      containers = $(".gallery-icon");
      images = [];
      for (_i = 0, _len = containers.length; _i < _len; _i++) {
        container = containers[_i];
        container = $(container);
        image_el = container.find("img").first();
        images.push({
          image_el: image_el,
          src: image_el.attr("src").split("?")[0],
          caption: container.next(".gallery-caption").text()
        });
      }
      console.dir(images);
      new BiggerPicture.Gallery(images);
    }

    return theChive;

  })();

  new theChive();

}).call(this);
